package hust.shop.mapper;

import hust.shop.pojo.Address;
import hust.shop.pojo.AddressExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AddressMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table address
	 * @mbggenerated  Sun Apr 12 15:52:42 CST 2015
	 */
	int countByExample(AddressExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table address
	 * @mbggenerated  Sun Apr 12 15:52:42 CST 2015
	 */
	int deleteByExample(AddressExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table address
	 * @mbggenerated  Sun Apr 12 15:52:42 CST 2015
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table address
	 * @mbggenerated  Sun Apr 12 15:52:42 CST 2015
	 */
	int insert(Address record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table address
	 * @mbggenerated  Sun Apr 12 15:52:42 CST 2015
	 */
	int insertSelective(Address record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table address
	 * @mbggenerated  Sun Apr 12 15:52:42 CST 2015
	 */
	List<Address> selectByExample(AddressExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table address
	 * @mbggenerated  Sun Apr 12 15:52:42 CST 2015
	 */
	Address selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table address
	 * @mbggenerated  Sun Apr 12 15:52:42 CST 2015
	 */
	int updateByExampleSelective(@Param("record") Address record,
			@Param("example") AddressExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table address
	 * @mbggenerated  Sun Apr 12 15:52:42 CST 2015
	 */
	int updateByExample(@Param("record") Address record,
			@Param("example") AddressExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table address
	 * @mbggenerated  Sun Apr 12 15:52:42 CST 2015
	 */
	int updateByPrimaryKeySelective(Address record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table address
	 * @mbggenerated  Sun Apr 12 15:52:42 CST 2015
	 */
	int updateByPrimaryKey(Address record);
}