package hust.shop.mapper;

import hust.shop.pojo.Cart;
import hust.shop.pojo.CartExample;
import hust.shop.pojo.CartInfo;
import hust.shop.pojo.Product;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import edu.hust.smartcommunity.paginator.domain.PageBounds;
import edu.hust.smartcommunity.paginator.domain.PageList;

public interface CartMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cart
	 * @mbggenerated  Fri Apr 17 10:24:05 CST 2015
	 */
	int countByExample(CartExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cart
	 * @mbggenerated  Fri Apr 17 10:24:05 CST 2015
	 */
	int deleteByExample(CartExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cart
	 * @mbggenerated  Fri Apr 17 10:24:05 CST 2015
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cart
	 * @mbggenerated  Fri Apr 17 10:24:05 CST 2015
	 */
	int insert(Cart record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cart
	 * @mbggenerated  Fri Apr 17 10:24:05 CST 2015
	 */
	int insertSelective(Cart record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cart
	 * @mbggenerated  Fri Apr 17 10:24:05 CST 2015
	 */
	List<Cart> selectByExample(CartExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cart
	 * @mbggenerated  Fri Apr 17 10:24:05 CST 2015
	 */
	Cart selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cart
	 * @mbggenerated  Fri Apr 17 10:24:05 CST 2015
	 */
	int updateByExampleSelective(@Param("record") Cart record,
			@Param("example") CartExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cart
	 * @mbggenerated  Fri Apr 17 10:24:05 CST 2015
	 */
	int updateByExample(@Param("record") Cart record,
			@Param("example") CartExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cart
	 * @mbggenerated  Fri Apr 17 10:24:05 CST 2015
	 */
	int updateByPrimaryKeySelective(Cart record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cart
	 * @mbggenerated  Fri Apr 17 10:24:05 CST 2015
	 */
	int updateByPrimaryKey(Cart record);

	//add
    PageList<CartInfo> selectByPage(@Param("id")Integer id,PageBounds pageBounds);
}