package hust.shop.mapper;

import hust.shop.pojo.Image;
import hust.shop.pojo.ImageExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ImageMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table image
	 * @mbggenerated  Sat Apr 04 16:10:18 CST 2015
	 */
	int countByExample(ImageExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table image
	 * @mbggenerated  Sat Apr 04 16:10:18 CST 2015
	 */
	int deleteByExample(ImageExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table image
	 * @mbggenerated  Sat Apr 04 16:10:18 CST 2015
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table image
	 * @mbggenerated  Sat Apr 04 16:10:18 CST 2015
	 */
	int insert(Image record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table image
	 * @mbggenerated  Sat Apr 04 16:10:18 CST 2015
	 */
	int insertSelective(Image record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table image
	 * @mbggenerated  Sat Apr 04 16:10:18 CST 2015
	 */
	List<Image> selectByExample(ImageExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table image
	 * @mbggenerated  Sat Apr 04 16:10:18 CST 2015
	 */
	Image selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table image
	 * @mbggenerated  Sat Apr 04 16:10:18 CST 2015
	 */
	int updateByExampleSelective(@Param("record") Image record,
			@Param("example") ImageExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table image
	 * @mbggenerated  Sat Apr 04 16:10:18 CST 2015
	 */
	int updateByExample(@Param("record") Image record,
			@Param("example") ImageExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table image
	 * @mbggenerated  Sat Apr 04 16:10:18 CST 2015
	 */
	int updateByPrimaryKeySelective(Image record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table image
	 * @mbggenerated  Sat Apr 04 16:10:18 CST 2015
	 */
	int updateByPrimaryKey(Image record);
}