package hust.shop.mapper;

import hust.shop.pojo.Orders;
import hust.shop.pojo.OrdersExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import edu.hust.smartcommunity.paginator.domain.PageBounds;
import edu.hust.smartcommunity.paginator.domain.PageList;

public interface OrdersMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orders
	 * @mbggenerated  Fri Apr 17 15:59:21 CST 2015
	 */
	int countByExample(OrdersExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orders
	 * @mbggenerated  Fri Apr 17 15:59:21 CST 2015
	 */
	int deleteByExample(OrdersExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orders
	 * @mbggenerated  Fri Apr 17 15:59:21 CST 2015
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orders
	 * @mbggenerated  Fri Apr 17 15:59:21 CST 2015
	 */
	int insert(Orders record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orders
	 * @mbggenerated  Fri Apr 17 15:59:21 CST 2015
	 */
	int insertSelective(Orders record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orders
	 * @mbggenerated  Fri Apr 17 15:59:21 CST 2015
	 */
	List<Orders> selectByExample(OrdersExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orders
	 * @mbggenerated  Fri Apr 17 15:59:21 CST 2015
	 */
	Orders selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orders
	 * @mbggenerated  Fri Apr 17 15:59:21 CST 2015
	 */
	int updateByExampleSelective(@Param("record") Orders record,
			@Param("example") OrdersExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orders
	 * @mbggenerated  Fri Apr 17 15:59:21 CST 2015
	 */
	int updateByExample(@Param("record") Orders record,
			@Param("example") OrdersExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orders
	 * @mbggenerated  Fri Apr 17 15:59:21 CST 2015
	 */
	int updateByPrimaryKeySelective(Orders record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orders
	 * @mbggenerated  Fri Apr 17 15:59:21 CST 2015
	 */
	int updateByPrimaryKey(Orders record);

	/** add_y */

	int deleteByOrderNumber(String orderNumber);

    PageList<Orders> getOrders(@Param("example") OrdersExample ordersExample,PageBounds pageBounds);
    PageList<Orders> getOrders(@Param("example") OrdersExample ordersExample);
	/** addend_y */
}