package hust.shop.mapper;

import hust.shop.pojo.OrdersPropertyValue;
import hust.shop.pojo.OrdersPropertyValueExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrdersPropertyValueMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders_property_value
     *
     * @mbggenerated Mon Apr 13 14:42:40 CST 2015
     */
    int countByExample(OrdersPropertyValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders_property_value
     *
     * @mbggenerated Mon Apr 13 14:42:40 CST 2015
     */
    int deleteByExample(OrdersPropertyValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders_property_value
     *
     * @mbggenerated Mon Apr 13 14:42:40 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders_property_value
     *
     * @mbggenerated Mon Apr 13 14:42:40 CST 2015
     */
    int insert(OrdersPropertyValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders_property_value
     *
     * @mbggenerated Mon Apr 13 14:42:40 CST 2015
     */
    int insertSelective(OrdersPropertyValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders_property_value
     *
     * @mbggenerated Mon Apr 13 14:42:40 CST 2015
     */
    List<OrdersPropertyValue> selectByExample(OrdersPropertyValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders_property_value
     *
     * @mbggenerated Mon Apr 13 14:42:40 CST 2015
     */
    OrdersPropertyValue selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders_property_value
     *
     * @mbggenerated Mon Apr 13 14:42:40 CST 2015
     */
    int updateByExampleSelective(@Param("record") OrdersPropertyValue record, @Param("example") OrdersPropertyValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders_property_value
     *
     * @mbggenerated Mon Apr 13 14:42:40 CST 2015
     */
    int updateByExample(@Param("record") OrdersPropertyValue record, @Param("example") OrdersPropertyValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders_property_value
     *
     * @mbggenerated Mon Apr 13 14:42:40 CST 2015
     */
    int updateByPrimaryKeySelective(OrdersPropertyValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders_property_value
     *
     * @mbggenerated Mon Apr 13 14:42:40 CST 2015
     */
    int updateByPrimaryKey(OrdersPropertyValue record);
}