package hust.shop.mapper;

import hust.shop.pojo.ProductProperty;
import hust.shop.pojo.ProductPropertyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProductPropertyMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_property
	 * @mbggenerated  Sat Apr 04 16:10:18 CST 2015
	 */
	int countByExample(ProductPropertyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_property
	 * @mbggenerated  Sat Apr 04 16:10:18 CST 2015
	 */
	int deleteByExample(ProductPropertyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_property
	 * @mbggenerated  Sat Apr 04 16:10:18 CST 2015
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_property
	 * @mbggenerated  Sat Apr 04 16:10:18 CST 2015
	 */
	int insert(ProductProperty record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_property
	 * @mbggenerated  Sat Apr 04 16:10:18 CST 2015
	 */
	int insertSelective(ProductProperty record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_property
	 * @mbggenerated  Sat Apr 04 16:10:18 CST 2015
	 */
	List<ProductProperty> selectByExample(ProductPropertyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_property
	 * @mbggenerated  Sat Apr 04 16:10:18 CST 2015
	 */
	ProductProperty selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_property
	 * @mbggenerated  Sat Apr 04 16:10:18 CST 2015
	 */
	int updateByExampleSelective(@Param("record") ProductProperty record,
			@Param("example") ProductPropertyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_property
	 * @mbggenerated  Sat Apr 04 16:10:18 CST 2015
	 */
	int updateByExample(@Param("record") ProductProperty record,
			@Param("example") ProductPropertyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_property
	 * @mbggenerated  Sat Apr 04 16:10:18 CST 2015
	 */
	int updateByPrimaryKeySelective(ProductProperty record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_property
	 * @mbggenerated  Sat Apr 04 16:10:18 CST 2015
	 */
	int updateByPrimaryKey(ProductProperty record);
}