package hust.shop.mapper;

import hust.shop.pojo.ProductPropertyValue;
import hust.shop.pojo.ProductPropertyValueExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProductPropertyValueMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_property_value
	 * @mbggenerated  Tue Apr 07 18:57:15 CST 2015
	 */
	int countByExample(ProductPropertyValueExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_property_value
	 * @mbggenerated  Tue Apr 07 18:57:15 CST 2015
	 */
	int deleteByExample(ProductPropertyValueExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_property_value
	 * @mbggenerated  Tue Apr 07 18:57:15 CST 2015
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_property_value
	 * @mbggenerated  Tue Apr 07 18:57:15 CST 2015
	 */
	int insert(ProductPropertyValue record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_property_value
	 * @mbggenerated  Tue Apr 07 18:57:15 CST 2015
	 */
	int insertSelective(ProductPropertyValue record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_property_value
	 * @mbggenerated  Tue Apr 07 18:57:15 CST 2015
	 */
	List<ProductPropertyValue> selectByExample(
			ProductPropertyValueExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_property_value
	 * @mbggenerated  Tue Apr 07 18:57:15 CST 2015
	 */
	ProductPropertyValue selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_property_value
	 * @mbggenerated  Tue Apr 07 18:57:15 CST 2015
	 */
	int updateByExampleSelective(@Param("record") ProductPropertyValue record,
			@Param("example") ProductPropertyValueExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_property_value
	 * @mbggenerated  Tue Apr 07 18:57:15 CST 2015
	 */
	int updateByExample(@Param("record") ProductPropertyValue record,
			@Param("example") ProductPropertyValueExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_property_value
	 * @mbggenerated  Tue Apr 07 18:57:15 CST 2015
	 */
	int updateByPrimaryKeySelective(ProductPropertyValue record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_property_value
	 * @mbggenerated  Tue Apr 07 18:57:15 CST 2015
	 */
	int updateByPrimaryKey(ProductPropertyValue record);
}