package hust.shop.mapper;

import hust.shop.pojo.ProductType;
import hust.shop.pojo.ProductTypeExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import edu.hust.smartcommunity.paginator.domain.PageBounds;
import edu.hust.smartcommunity.paginator.domain.PageList;

public interface ProductTypeMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_type
	 * @mbggenerated  Wed Apr 22 15:59:33 CST 2015
	 */
	int countByExample(ProductTypeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_type
	 * @mbggenerated  Wed Apr 22 15:59:33 CST 2015
	 */
	int deleteByExample(ProductTypeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_type
	 * @mbggenerated  Wed Apr 22 15:59:33 CST 2015
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_type
	 * @mbggenerated  Wed Apr 22 15:59:33 CST 2015
	 */
	int insert(ProductType record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_type
	 * @mbggenerated  Wed Apr 22 15:59:33 CST 2015
	 */
	int insertSelective(ProductType record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_type
	 * @mbggenerated  Wed Apr 22 15:59:33 CST 2015
	 */
	List<ProductType> selectByExample(ProductTypeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_type
	 * @mbggenerated  Wed Apr 22 15:59:33 CST 2015
	 */
	ProductType selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_type
	 * @mbggenerated  Wed Apr 22 15:59:33 CST 2015
	 */
	int updateByExampleSelective(@Param("record") ProductType record,
			@Param("example") ProductTypeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_type
	 * @mbggenerated  Wed Apr 22 15:59:33 CST 2015
	 */
	int updateByExample(@Param("record") ProductType record,
			@Param("example") ProductTypeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_type
	 * @mbggenerated  Wed Apr 22 15:59:33 CST 2015
	 */
	int updateByPrimaryKeySelective(ProductType record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_type
	 * @mbggenerated  Wed Apr 22 15:59:33 CST 2015
	 */
	int updateByPrimaryKey(ProductType record);

	PageList<ProductType> selectByExample(ProductTypeExample example,PageBounds pageBounds);
}