package hust.shop.mapper;

import hust.shop.pojo.Product;
import hust.shop.pojo.ProductExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import edu.hust.smartcommunity.paginator.domain.PageBounds;
import edu.hust.smartcommunity.paginator.domain.PageList;

public interface ProductMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product
	 * @mbggenerated  Fri Apr 10 15:07:57 CST 2015
	 */
	int countByExample(ProductExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product
	 * @mbggenerated  Fri Apr 10 15:07:57 CST 2015
	 */
	int deleteByExample(ProductExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product
	 * @mbggenerated  Fri Apr 10 15:07:57 CST 2015
	 */
	int deleteByPrimaryKey(Integer id);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product
	 * @mbggenerated  Fri Apr 10 15:07:57 CST 2015
	 */
	int insert(Product record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product
	 * @mbggenerated  Fri Apr 10 15:07:57 CST 2015
	 */
	int insertSelective(Product record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product
	 * @mbggenerated  Fri Apr 10 15:07:57 CST 2015
	 */
	List<Product> selectByExample(ProductExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product
	 * @mbggenerated  Fri Apr 10 15:07:57 CST 2015
	 */
	Product selectByPrimaryKey(Integer id);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product
	 * @mbggenerated  Fri Apr 10 15:07:57 CST 2015
	 */
	int updateByExampleSelective(@Param("record") Product record,
			@Param("example") ProductExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product
	 * @mbggenerated  Fri Apr 10 15:07:57 CST 2015
	 */
	int updateByExample(@Param("record") Product record,
			@Param("example") ProductExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product
	 * @mbggenerated  Fri Apr 10 15:07:57 CST 2015
	 */
	int updateByPrimaryKeySelective(Product record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product
	 * @mbggenerated  Fri Apr 10 15:07:57 CST 2015
	 */
	int updateByPrimaryKey(Product record);
	PageList<Product> selectByExample(ProductExample example,PageBounds pageBounds);
	PageList<Product> selectProductWithImage(ProductExample example,PageBounds pageBounds);

	Product selectProductWithImageById(@Param("id") Integer id);
}