package hust.shop.mapper;

import hust.shop.pojo.Shop;
import hust.shop.pojo.ShopExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import edu.hust.smartcommunity.paginator.domain.PageBounds;
import edu.hust.smartcommunity.paginator.domain.PageList;

public interface ShopMapper {
	
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shop
	 * @mbggenerated  Fri Apr 03 17:20:12 CST 2015
	 */
	int countByExample(ShopExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shop
	 * @mbggenerated  Fri Apr 03 17:20:12 CST 2015
	 */
	int deleteByExample(ShopExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shop
	 * @mbggenerated  Fri Apr 03 17:20:12 CST 2015
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shop
	 * @mbggenerated  Fri Apr 03 17:20:12 CST 2015
	 */
	int insert(Shop record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shop
	 * @mbggenerated  Fri Apr 03 17:20:12 CST 2015
	 */
	int insertSelective(Shop record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shop
	 * @mbggenerated  Fri Apr 03 17:20:12 CST 2015
	 */
	List<Shop> selectByExample(ShopExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shop
	 * @mbggenerated  Fri Apr 03 17:20:12 CST 2015
	 */
	Shop selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shop
	 * @mbggenerated  Fri Apr 03 17:20:12 CST 2015
	 */
	int updateByExampleSelective(@Param("record") Shop record,
			@Param("example") ShopExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shop
	 * @mbggenerated  Fri Apr 03 17:20:12 CST 2015
	 */
	int updateByExample(@Param("record") Shop record,
			@Param("example") ShopExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shop
	 * @mbggenerated  Fri Apr 03 17:20:12 CST 2015
	 */
	int updateByPrimaryKeySelective(Shop record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shop
	 * @mbggenerated  Fri Apr 03 17:20:12 CST 2015
	 */
	int updateByPrimaryKey(Shop record);
	
	PageList<Shop> selectByExample(ShopExample shopExample,PageBounds pageBounds);
}