package hust.shop.pojo;

public class Address {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column address.id
	 * @mbggenerated  Sun Apr 12 15:52:42 CST 2015
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column address.user_id
	 * @mbggenerated  Sun Apr 12 15:52:42 CST 2015
	 */
	private Integer userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column address.address
	 * @mbggenerated  Sun Apr 12 15:52:42 CST 2015
	 */
	private String address;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column address.isDefault
	 * @mbggenerated  Sun Apr 12 15:52:42 CST 2015
	 */
	private Boolean isdefault;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column address.name
	 * @mbggenerated  Sun Apr 12 15:52:42 CST 2015
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column address.telephone
	 * @mbggenerated  Sun Apr 12 15:52:42 CST 2015
	 */
	private String telephone;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column address.id
	 * @return  the value of address.id
	 * @mbggenerated  Sun Apr 12 15:52:42 CST 2015
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column address.id
	 * @param id  the value for address.id
	 * @mbggenerated  Sun Apr 12 15:52:42 CST 2015
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column address.user_id
	 * @return  the value of address.user_id
	 * @mbggenerated  Sun Apr 12 15:52:42 CST 2015
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column address.user_id
	 * @param userId  the value for address.user_id
	 * @mbggenerated  Sun Apr 12 15:52:42 CST 2015
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column address.address
	 * @return  the value of address.address
	 * @mbggenerated  Sun Apr 12 15:52:42 CST 2015
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column address.address
	 * @param address  the value for address.address
	 * @mbggenerated  Sun Apr 12 15:52:42 CST 2015
	 */
	public void setAddress(String address) {
		this.address = address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column address.isDefault
	 * @return  the value of address.isDefault
	 * @mbggenerated  Sun Apr 12 15:52:42 CST 2015
	 */
	public Boolean getIsdefault() {
		return isdefault;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column address.isDefault
	 * @param isdefault  the value for address.isDefault
	 * @mbggenerated  Sun Apr 12 15:52:42 CST 2015
	 */
	public void setIsdefault(Boolean isdefault) {
		this.isdefault = isdefault;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column address.name
	 * @return  the value of address.name
	 * @mbggenerated  Sun Apr 12 15:52:42 CST 2015
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column address.name
	 * @param name  the value for address.name
	 * @mbggenerated  Sun Apr 12 15:52:42 CST 2015
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column address.telephone
	 * @return  the value of address.telephone
	 * @mbggenerated  Sun Apr 12 15:52:42 CST 2015
	 */
	public String getTelephone() {
		return telephone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column address.telephone
	 * @param telephone  the value for address.telephone
	 * @mbggenerated  Sun Apr 12 15:52:42 CST 2015
	 */
	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}
}