package hust.shop.pojo;

public class CommentType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment_type.id
     *
     * @mbggenerated Wed Apr 08 12:26:24 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment_type.name
     *
     * @mbggenerated Wed Apr 08 12:26:24 CST 2015
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment_type.id
     *
     * @return the value of comment_type.id
     *
     * @mbggenerated Wed Apr 08 12:26:24 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment_type.id
     *
     * @param id the value for comment_type.id
     *
     * @mbggenerated Wed Apr 08 12:26:24 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment_type.name
     *
     * @return the value of comment_type.name
     *
     * @mbggenerated Wed Apr 08 12:26:24 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment_type.name
     *
     * @param name the value for comment_type.name
     *
     * @mbggenerated Wed Apr 08 12:26:24 CST 2015
     */
    public void setName(String name) {
        this.name = name;
    }
}