package hust.shop.pojo;

import java.util.Date;

public class Comment {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comment.id
	 * @mbggenerated  Wed Apr 08 13:21:24 CST 2015
	 */
	private Integer id;
	private String username;
	private String commentType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comment.product_id
	 * @mbggenerated  Wed Apr 08 13:21:24 CST 2015
	 */
	private Integer productId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comment.user_id
	 * @mbggenerated  Wed Apr 08 13:21:24 CST 2015
	 */
	private Integer userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comment.comment_type_id
	 * @mbggenerated  Wed Apr 08 13:21:24 CST 2015
	 */
	private Integer commentTypeId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comment.comment
	 * @mbggenerated  Wed Apr 08 13:21:24 CST 2015
	 */
	private String comment;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comment.append
	 * @mbggenerated  Wed Apr 08 13:21:24 CST 2015
	 */
	private String append;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comment.time
	 * @mbggenerated  Wed Apr 08 13:21:24 CST 2015
	 */
	private Date time;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comment.append_time
	 * @mbggenerated  Wed Apr 08 13:21:24 CST 2015
	 */
	private Date appendTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comment.id
	 * @return  the value of comment.id
	 * @mbggenerated  Wed Apr 08 13:21:24 CST 2015
	 */
	public Integer getId() {
		return id;
	}
	

	public String getUsername() {
		return username;
	}


	public void setUsername(String username) {
		this.username = username;
	}


	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comment.id
	 * @param id  the value for comment.id
	 * @mbggenerated  Wed Apr 08 13:21:24 CST 2015
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comment.product_id
	 * @return  the value of comment.product_id
	 * @mbggenerated  Wed Apr 08 13:21:24 CST 2015
	 */
	public Integer getProductId() {
		return productId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comment.product_id
	 * @param productId  the value for comment.product_id
	 * @mbggenerated  Wed Apr 08 13:21:24 CST 2015
	 */
	public void setProductId(Integer productId) {
		this.productId = productId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comment.user_id
	 * @return  the value of comment.user_id
	 * @mbggenerated  Wed Apr 08 13:21:24 CST 2015
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comment.user_id
	 * @param userId  the value for comment.user_id
	 * @mbggenerated  Wed Apr 08 13:21:24 CST 2015
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comment.comment_type_id
	 * @return  the value of comment.comment_type_id
	 * @mbggenerated  Wed Apr 08 13:21:24 CST 2015
	 */
	public Integer getCommentTypeId() {
		return commentTypeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comment.comment_type_id
	 * @param commentTypeId  the value for comment.comment_type_id
	 * @mbggenerated  Wed Apr 08 13:21:24 CST 2015
	 */
	public void setCommentTypeId(Integer commentTypeId) {
		this.commentTypeId = commentTypeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comment.comment
	 * @return  the value of comment.comment
	 * @mbggenerated  Wed Apr 08 13:21:24 CST 2015
	 */
	public String getComment() {
		return comment;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comment.comment
	 * @param comment  the value for comment.comment
	 * @mbggenerated  Wed Apr 08 13:21:24 CST 2015
	 */
	public void setComment(String comment) {
		this.comment = comment;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comment.append
	 * @return  the value of comment.append
	 * @mbggenerated  Wed Apr 08 13:21:24 CST 2015
	 */
	public String getAppend() {
		return append;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comment.append
	 * @param append  the value for comment.append
	 * @mbggenerated  Wed Apr 08 13:21:24 CST 2015
	 */
	public void setAppend(String append) {
		this.append = append;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comment.time
	 * @return  the value of comment.time
	 * @mbggenerated  Wed Apr 08 13:21:24 CST 2015
	 */
	public Date getTime() {
		return time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comment.time
	 * @param time  the value for comment.time
	 * @mbggenerated  Wed Apr 08 13:21:24 CST 2015
	 */
	public void setTime(Date time) {
		this.time = time;
	}

	public String getCommentType() {
		return commentType;
	}


	public void setCommentType(String commentType) {
		this.commentType = commentType;
	}


	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comment.append_time
	 * @return  the value of comment.append_time
	 * @mbggenerated  Wed Apr 08 13:21:24 CST 2015
	 */
	public Date getAppendTime() {
		return appendTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comment.append_time
	 * @param appendTime  the value for comment.append_time
	 * @mbggenerated  Wed Apr 08 13:21:24 CST 2015
	 */
	public void setAppendTime(Date appendTime) {
		this.appendTime = appendTime;
	}
}