package hust.shop.pojo;

import java.util.Date;

public class Image {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column image.id
	 * @mbggenerated  Sat Apr 04 16:10:18 CST 2015
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column image.product_id
	 * @mbggenerated  Sat Apr 04 16:10:18 CST 2015
	 */
	private Integer productId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column image.url
	 * @mbggenerated  Sat Apr 04 16:10:18 CST 2015
	 */
	private String url;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column image.datetime
	 * @mbggenerated  Sat Apr 04 16:10:18 CST 2015
	 */
	private Date datetime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column image.id
	 * @return  the value of image.id
	 * @mbggenerated  Sat Apr 04 16:10:18 CST 2015
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column image.id
	 * @param id  the value for image.id
	 * @mbggenerated  Sat Apr 04 16:10:18 CST 2015
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column image.product_id
	 * @return  the value of image.product_id
	 * @mbggenerated  Sat Apr 04 16:10:18 CST 2015
	 */
	public Integer getProductId() {
		return productId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column image.product_id
	 * @param productId  the value for image.product_id
	 * @mbggenerated  Sat Apr 04 16:10:18 CST 2015
	 */
	public void setProductId(Integer productId) {
		this.productId = productId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column image.url
	 * @return  the value of image.url
	 * @mbggenerated  Sat Apr 04 16:10:18 CST 2015
	 */
	public String getUrl() {
		return url;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column image.url
	 * @param url  the value for image.url
	 * @mbggenerated  Sat Apr 04 16:10:18 CST 2015
	 */
	public void setUrl(String url) {
		this.url = url;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column image.datetime
	 * @return  the value of image.datetime
	 * @mbggenerated  Sat Apr 04 16:10:18 CST 2015
	 */
	public Date getDatetime() {
		return datetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column image.datetime
	 * @param datetime  the value for image.datetime
	 * @mbggenerated  Sat Apr 04 16:10:18 CST 2015
	 */
	public void setDatetime(Date datetime) {
		this.datetime = datetime;
	}
}