package hust.shop.pojo;

import java.util.Date;

public class Orders {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column orders.id
	 * @mbggenerated  Fri Apr 17 15:59:21 CST 2015
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column orders.order_number
	 * @mbggenerated  Fri Apr 17 15:59:21 CST 2015
	 */
	private String orderNumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column orders.shop_id
	 * @mbggenerated  Fri Apr 17 15:59:21 CST 2015
	 */
	private Integer shopId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column orders.user_id
	 * @mbggenerated  Fri Apr 17 15:59:21 CST 2015
	 */
	private Integer userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column orders.address
	 * @mbggenerated  Fri Apr 17 15:59:21 CST 2015
	 */
	private String address;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column orders.telephone
	 * @mbggenerated  Fri Apr 17 15:59:21 CST 2015
	 */
	private String telephone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column orders.total_price
	 * @mbggenerated  Fri Apr 17 15:59:21 CST 2015
	 */
	private Float totalPrice;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column orders.order_time
	 * @mbggenerated  Fri Apr 17 15:59:21 CST 2015
	 */
	private Date orderTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column orders.recipient
	 * @mbggenerated  Fri Apr 17 15:59:21 CST 2015
	 */
	private String recipient;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column orders.receipt_state
	 * @mbggenerated  Fri Apr 17 15:59:21 CST 2015
	 */
	private Integer receiptState;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column orders.confirmed
	 * @mbggenerated  Fri Apr 17 15:59:21 CST 2015
	 */
	private Boolean confirmed;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column orders.id
	 * @return  the value of orders.id
	 * @mbggenerated  Fri Apr 17 15:59:21 CST 2015
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column orders.id
	 * @param id  the value for orders.id
	 * @mbggenerated  Fri Apr 17 15:59:21 CST 2015
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column orders.order_number
	 * @return  the value of orders.order_number
	 * @mbggenerated  Fri Apr 17 15:59:21 CST 2015
	 */
	public String getOrderNumber() {
		return orderNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column orders.order_number
	 * @param orderNumber  the value for orders.order_number
	 * @mbggenerated  Fri Apr 17 15:59:21 CST 2015
	 */
	public void setOrderNumber(String orderNumber) {
		this.orderNumber = orderNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column orders.shop_id
	 * @return  the value of orders.shop_id
	 * @mbggenerated  Fri Apr 17 15:59:21 CST 2015
	 */
	public Integer getShopId() {
		return shopId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column orders.shop_id
	 * @param shopId  the value for orders.shop_id
	 * @mbggenerated  Fri Apr 17 15:59:21 CST 2015
	 */
	public void setShopId(Integer shopId) {
		this.shopId = shopId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column orders.user_id
	 * @return  the value of orders.user_id
	 * @mbggenerated  Fri Apr 17 15:59:21 CST 2015
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column orders.user_id
	 * @param userId  the value for orders.user_id
	 * @mbggenerated  Fri Apr 17 15:59:21 CST 2015
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column orders.address
	 * @return  the value of orders.address
	 * @mbggenerated  Fri Apr 17 15:59:21 CST 2015
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column orders.address
	 * @param address  the value for orders.address
	 * @mbggenerated  Fri Apr 17 15:59:21 CST 2015
	 */
	public void setAddress(String address) {
		this.address = address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column orders.telephone
	 * @return  the value of orders.telephone
	 * @mbggenerated  Fri Apr 17 15:59:21 CST 2015
	 */
	public String getTelephone() {
		return telephone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column orders.telephone
	 * @param telephone  the value for orders.telephone
	 * @mbggenerated  Fri Apr 17 15:59:21 CST 2015
	 */
	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column orders.total_price
	 * @return  the value of orders.total_price
	 * @mbggenerated  Fri Apr 17 15:59:21 CST 2015
	 */
	public Float getTotalPrice() {
		return totalPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column orders.total_price
	 * @param totalPrice  the value for orders.total_price
	 * @mbggenerated  Fri Apr 17 15:59:21 CST 2015
	 */
	public void setTotalPrice(Float totalPrice) {
		this.totalPrice = totalPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column orders.order_time
	 * @return  the value of orders.order_time
	 * @mbggenerated  Fri Apr 17 15:59:21 CST 2015
	 */
	public Date getOrderTime() {
		return orderTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column orders.order_time
	 * @param orderTime  the value for orders.order_time
	 * @mbggenerated  Fri Apr 17 15:59:21 CST 2015
	 */
	public void setOrderTime(Date orderTime) {
		this.orderTime = orderTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column orders.recipient
	 * @return  the value of orders.recipient
	 * @mbggenerated  Fri Apr 17 15:59:21 CST 2015
	 */
	public String getRecipient() {
		return recipient;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column orders.recipient
	 * @param recipient  the value for orders.recipient
	 * @mbggenerated  Fri Apr 17 15:59:21 CST 2015
	 */
	public void setRecipient(String recipient) {
		this.recipient = recipient;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column orders.receipt_state
	 * @return  the value of orders.receipt_state
	 * @mbggenerated  Fri Apr 17 15:59:21 CST 2015
	 */
	public Integer getReceiptState() {
		return receiptState;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column orders.receipt_state
	 * @param receiptState  the value for orders.receipt_state
	 * @mbggenerated  Fri Apr 17 15:59:21 CST 2015
	 */
	public void setReceiptState(Integer receiptState) {
		this.receiptState = receiptState;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column orders.confirmed
	 * @return  the value of orders.confirmed
	 * @mbggenerated  Fri Apr 17 15:59:21 CST 2015
	 */
	public Boolean getConfirmed() {
		return confirmed;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column orders.confirmed
	 * @param confirmed  the value for orders.confirmed
	 * @mbggenerated  Fri Apr 17 15:59:21 CST 2015
	 */
	public void setConfirmed(Boolean confirmed) {
		this.confirmed = confirmed;
	}


	java.util.List<OrdersPropertyValue> ordersPropertyValues;

	public java.util.List<OrdersPropertyValue> getOrdersPropertyValues() {
		return ordersPropertyValues;
	}

	public void setOrdersPropertyValues(
			java.util.List<OrdersPropertyValue> ordersPropertyValues) {
		this.ordersPropertyValues = ordersPropertyValues;
	}
	/** add_y */
	java.util.List<OrdersProduct> ordersProducts;

	public java.util.List<OrdersProduct> getOrdersProducts() {
		return ordersProducts;
	}

	public void setOrdersProducts(java.util.List<OrdersProduct> ordersProducts) {
		this.ordersProducts = ordersProducts;
	}

	/** addend_y */
}