package hust.shop.pojo;

public class OrdersPropertyValue {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders_property_value.id
     *
     * @mbggenerated Mon Apr 13 14:42:40 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders_property_value.order_number
     *
     * @mbggenerated Mon Apr 13 14:42:40 CST 2015
     */
    private String orderNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders_property_value.property_value
     *
     * @mbggenerated Mon Apr 13 14:42:40 CST 2015
     */
    private String propertyValue;
    private String property;
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders_property_value.id
     *
     * @return the value of orders_property_value.id
     *
     * @mbggenerated Mon Apr 13 14:42:40 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders_property_value.id
     *
     * @param id the value for orders_property_value.id
     *
     * @mbggenerated Mon Apr 13 14:42:40 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders_property_value.order_number
     *
     * @return the value of orders_property_value.order_number
     *
     * @mbggenerated Mon Apr 13 14:42:40 CST 2015
     */
    public String getOrderNumber() {
        return orderNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders_property_value.order_number
     *
     * @param orderNumber the value for orders_property_value.order_number
     *
     * @mbggenerated Mon Apr 13 14:42:40 CST 2015
     */
    public void setOrderNumber(String orderNumber) {
        this.orderNumber = orderNumber == null ? null : orderNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders_property_value.property_value
     *
     * @return the value of orders_property_value.property_value
     *
     * @mbggenerated Mon Apr 13 14:42:40 CST 2015
     */
    public String getPropertyValue() {
        return propertyValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders_property_value.property_value
     *
     * @param propertyValue the value for orders_property_value.property_value
     *
     * @mbggenerated Mon Apr 13 14:42:40 CST 2015
     */
    public void setPropertyValue(String propertyValue) {
        this.propertyValue = propertyValue == null ? null : propertyValue.trim();
    }
    public String getProperty() {
        return property;
    }
    public void setProperty(String property) {
        this.property = property == null ? null : property.trim();
    }
}