package hust.shop.pojo;

public class OrdersProduct {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders_product.id
     *
     * @mbggenerated Fri Apr 17 15:59:21 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders_product.order_number
     *
     * @mbggenerated Fri Apr 17 15:59:21 CST 2015
     */
    private String orderNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders_product.product_id
     *
     * @mbggenerated Fri Apr 17 15:59:21 CST 2015
     */
    private Integer productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders_product.product_name
     *
     * @mbggenerated Fri Apr 17 15:59:21 CST 2015
     */
    private String productName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders_product.number
     *
     * @mbggenerated Fri Apr 17 15:59:21 CST 2015
     */
    private Integer number;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders_product.price
     *
     * @mbggenerated Fri Apr 17 15:59:21 CST 2015
     */
    private Float price;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders_product.id
     *
     * @return the value of orders_product.id
     *
     * @mbggenerated Fri Apr 17 15:59:21 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders_product.id
     *
     * @param id the value for orders_product.id
     *
     * @mbggenerated Fri Apr 17 15:59:21 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders_product.order_number
     *
     * @return the value of orders_product.order_number
     *
     * @mbggenerated Fri Apr 17 15:59:21 CST 2015
     */
    public String getOrderNumber() {
        return orderNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders_product.order_number
     *
     * @param orderNumber the value for orders_product.order_number
     *
     * @mbggenerated Fri Apr 17 15:59:21 CST 2015
     */
    public void setOrderNumber(String orderNumber) {
        this.orderNumber = orderNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders_product.product_id
     *
     * @return the value of orders_product.product_id
     *
     * @mbggenerated Fri Apr 17 15:59:21 CST 2015
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders_product.product_id
     *
     * @param productId the value for orders_product.product_id
     *
     * @mbggenerated Fri Apr 17 15:59:21 CST 2015
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders_product.product_name
     *
     * @return the value of orders_product.product_name
     *
     * @mbggenerated Fri Apr 17 15:59:21 CST 2015
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders_product.product_name
     *
     * @param productName the value for orders_product.product_name
     *
     * @mbggenerated Fri Apr 17 15:59:21 CST 2015
     */
    public void setProductName(String productName) {
        this.productName = productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders_product.number
     *
     * @return the value of orders_product.number
     *
     * @mbggenerated Fri Apr 17 15:59:21 CST 2015
     */
    public Integer getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders_product.number
     *
     * @param number the value for orders_product.number
     *
     * @mbggenerated Fri Apr 17 15:59:21 CST 2015
     */
    public void setNumber(Integer number) {
        this.number = number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders_product.price
     *
     * @return the value of orders_product.price
     *
     * @mbggenerated Fri Apr 17 15:59:21 CST 2015
     */
    public Float getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders_product.price
     *
     * @param price the value for orders_product.price
     *
     * @mbggenerated Fri Apr 17 15:59:21 CST 2015
     */
    public void setPrice(Float price) {
        this.price = price;
    }
}