package hust.shop.pojo;

import java.util.Date;

public class ProductType {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product_type.id
	 * @mbggenerated  Wed Apr 22 15:59:33 CST 2015
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product_type.type_name
	 * @mbggenerated  Wed Apr 22 15:59:33 CST 2015
	 */
	private String typeName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product_type.datetime
	 * @mbggenerated  Wed Apr 22 15:59:33 CST 2015
	 */
	private Date datetime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product_type.id
	 * @return  the value of product_type.id
	 * @mbggenerated  Wed Apr 22 15:59:33 CST 2015
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product_type.id
	 * @param id  the value for product_type.id
	 * @mbggenerated  Wed Apr 22 15:59:33 CST 2015
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product_type.type_name
	 * @return  the value of product_type.type_name
	 * @mbggenerated  Wed Apr 22 15:59:33 CST 2015
	 */
	public String getTypeName() {
		return typeName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product_type.type_name
	 * @param typeName  the value for product_type.type_name
	 * @mbggenerated  Wed Apr 22 15:59:33 CST 2015
	 */
	public void setTypeName(String typeName) {
		this.typeName = typeName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product_type.datetime
	 * @return  the value of product_type.datetime
	 * @mbggenerated  Wed Apr 22 15:59:33 CST 2015
	 */
	public Date getDatetime() {
		return datetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product_type.datetime
	 * @param datetime  the value for product_type.datetime
	 * @mbggenerated  Wed Apr 22 15:59:33 CST 2015
	 */
	public void setDatetime(Date datetime) {
		this.datetime = datetime;
	}
}