package hust.shop.pojo;

import java.util.Date;

public class ProductProperty {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product_property.id
	 * @mbggenerated  Sat Apr 04 16:10:18 CST 2015
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product_property.product_type_id
	 * @mbggenerated  Sat Apr 04 16:10:18 CST 2015
	 */
	private Integer productTypeId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product_property.name
	 * @mbggenerated  Sat Apr 04 16:10:18 CST 2015
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product_property.datetime
	 * @mbggenerated  Sat Apr 04 16:10:18 CST 2015
	 */
	private Date datetime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product_property.id
	 * @return  the value of product_property.id
	 * @mbggenerated  Sat Apr 04 16:10:18 CST 2015
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product_property.id
	 * @param id  the value for product_property.id
	 * @mbggenerated  Sat Apr 04 16:10:18 CST 2015
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product_property.product_type_id
	 * @return  the value of product_property.product_type_id
	 * @mbggenerated  Sat Apr 04 16:10:18 CST 2015
	 */
	public Integer getProductTypeId() {
		return productTypeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product_property.product_type_id
	 * @param productTypeId  the value for product_property.product_type_id
	 * @mbggenerated  Sat Apr 04 16:10:18 CST 2015
	 */
	public void setProductTypeId(Integer productTypeId) {
		this.productTypeId = productTypeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product_property.name
	 * @return  the value of product_property.name
	 * @mbggenerated  Sat Apr 04 16:10:18 CST 2015
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product_property.name
	 * @param name  the value for product_property.name
	 * @mbggenerated  Sat Apr 04 16:10:18 CST 2015
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product_property.datetime
	 * @return  the value of product_property.datetime
	 * @mbggenerated  Sat Apr 04 16:10:18 CST 2015
	 */
	public Date getDatetime() {
		return datetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product_property.datetime
	 * @param datetime  the value for product_property.datetime
	 * @mbggenerated  Sat Apr 04 16:10:18 CST 2015
	 */
	public void setDatetime(Date datetime) {
		this.datetime = datetime;
	}
}