package hust.shop.pojo;

public class ProductPropertyValue {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product_property_value.id
	 * @mbggenerated  Tue Apr 07 18:57:15 CST 2015
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product_property_value.product_id
	 * @mbggenerated  Tue Apr 07 18:57:15 CST 2015
	 */
	private Integer productId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product_property_value.property_value_id
	 * @mbggenerated  Tue Apr 07 18:57:15 CST 2015
	 */
	private Integer propertyValueId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product_property_value.id
	 * @return  the value of product_property_value.id
	 * @mbggenerated  Tue Apr 07 18:57:15 CST 2015
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product_property_value.id
	 * @param id  the value for product_property_value.id
	 * @mbggenerated  Tue Apr 07 18:57:15 CST 2015
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product_property_value.product_id
	 * @return  the value of product_property_value.product_id
	 * @mbggenerated  Tue Apr 07 18:57:15 CST 2015
	 */
	public Integer getProductId() {
		return productId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product_property_value.product_id
	 * @param productId  the value for product_property_value.product_id
	 * @mbggenerated  Tue Apr 07 18:57:15 CST 2015
	 */
	public void setProductId(Integer productId) {
		this.productId = productId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product_property_value.property_value_id
	 * @return  the value of product_property_value.property_value_id
	 * @mbggenerated  Tue Apr 07 18:57:15 CST 2015
	 */
	public Integer getPropertyValueId() {
		return propertyValueId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product_property_value.property_value_id
	 * @param propertyValueId  the value for product_property_value.property_value_id
	 * @mbggenerated  Tue Apr 07 18:57:15 CST 2015
	 */
	public void setPropertyValueId(Integer propertyValueId) {
		this.propertyValueId = propertyValueId;
	}
}