package hust.shop.pojo;

import java.util.ArrayList;
import java.util.List;
import java.util.Date;

public class PropertyValueExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table property_value
	 * @mbggenerated  Tue Apr 07 19:01:45 CST 2015
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table property_value
	 * @mbggenerated  Tue Apr 07 19:01:45 CST 2015
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table property_value
	 * @mbggenerated  Tue Apr 07 19:01:45 CST 2015
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table property_value
	 * @mbggenerated  Tue Apr 07 19:01:45 CST 2015
	 */
	public PropertyValueExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table property_value
	 * @mbggenerated  Tue Apr 07 19:01:45 CST 2015
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table property_value
	 * @mbggenerated  Tue Apr 07 19:01:45 CST 2015
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table property_value
	 * @mbggenerated  Tue Apr 07 19:01:45 CST 2015
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table property_value
	 * @mbggenerated  Tue Apr 07 19:01:45 CST 2015
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table property_value
	 * @mbggenerated  Tue Apr 07 19:01:45 CST 2015
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table property_value
	 * @mbggenerated  Tue Apr 07 19:01:45 CST 2015
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table property_value
	 * @mbggenerated  Tue Apr 07 19:01:45 CST 2015
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table property_value
	 * @mbggenerated  Tue Apr 07 19:01:45 CST 2015
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table property_value
	 * @mbggenerated  Tue Apr 07 19:01:45 CST 2015
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table property_value
	 * @mbggenerated  Tue Apr 07 19:01:45 CST 2015
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table property_value
	 * @mbggenerated  Tue Apr 07 19:01:45 CST 2015
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		
		public Criteria andadotIdIn(List<Integer> values) {
			addCriterion("a.id in", values, "a.id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andProductPropertyIdIsNull() {
			addCriterion("product_property_id is null");
			return (Criteria) this;
		}

		public Criteria andProductPropertyIdIsNotNull() {
			addCriterion("product_property_id is not null");
			return (Criteria) this;
		}

		public Criteria andProductPropertyIdEqualTo(Integer value) {
			addCriterion("product_property_id =", value, "productPropertyId");
			return (Criteria) this;
		}

		public Criteria andProductPropertyIdNotEqualTo(Integer value) {
			addCriterion("product_property_id <>", value, "productPropertyId");
			return (Criteria) this;
		}

		public Criteria andProductPropertyIdGreaterThan(Integer value) {
			addCriterion("product_property_id >", value, "productPropertyId");
			return (Criteria) this;
		}

		public Criteria andProductPropertyIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("product_property_id >=", value, "productPropertyId");
			return (Criteria) this;
		}

		public Criteria andProductPropertyIdLessThan(Integer value) {
			addCriterion("product_property_id <", value, "productPropertyId");
			return (Criteria) this;
		}

		public Criteria andProductPropertyIdLessThanOrEqualTo(Integer value) {
			addCriterion("product_property_id <=", value, "productPropertyId");
			return (Criteria) this;
		}

		public Criteria andProductPropertyIdIn(List<Integer> values) {
			addCriterion("product_property_id in", values, "productPropertyId");
			return (Criteria) this;
		}

		public Criteria andProductPropertyIdNotIn(List<Integer> values) {
			addCriterion("product_property_id not in", values,
					"productPropertyId");
			return (Criteria) this;
		}

		public Criteria andProductPropertyIdBetween(Integer value1,
				Integer value2) {
			addCriterion("product_property_id between", value1, value2,
					"productPropertyId");
			return (Criteria) this;
		}

		public Criteria andProductPropertyIdNotBetween(Integer value1,
				Integer value2) {
			addCriterion("product_property_id not between", value1, value2,
					"productPropertyId");
			return (Criteria) this;
		}

		public Criteria andNameIsNull() {
			addCriterion("name is null");
			return (Criteria) this;
		}

		public Criteria andNameIsNotNull() {
			addCriterion("name is not null");
			return (Criteria) this;
		}

		public Criteria andNameEqualTo(String value) {
			addCriterion("name =", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotEqualTo(String value) {
			addCriterion("name <>", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThan(String value) {
			addCriterion("name >", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThanOrEqualTo(String value) {
			addCriterion("name >=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThan(String value) {
			addCriterion("name <", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThanOrEqualTo(String value) {
			addCriterion("name <=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLike(String value) {
			addCriterion("name like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotLike(String value) {
			addCriterion("name not like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameIn(List<String> values) {
			addCriterion("name in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotIn(List<String> values) {
			addCriterion("name not in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameBetween(String value1, String value2) {
			addCriterion("name between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotBetween(String value1, String value2) {
			addCriterion("name not between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andDatetimeIsNull() {
			addCriterion("datetime is null");
			return (Criteria) this;
		}

		public Criteria andDatetimeIsNotNull() {
			addCriterion("datetime is not null");
			return (Criteria) this;
		}

		public Criteria andDatetimeEqualTo(Date value) {
			addCriterion("datetime =", value, "datetime");
			return (Criteria) this;
		}

		public Criteria andDatetimeNotEqualTo(Date value) {
			addCriterion("datetime <>", value, "datetime");
			return (Criteria) this;
		}

		public Criteria andDatetimeGreaterThan(Date value) {
			addCriterion("datetime >", value, "datetime");
			return (Criteria) this;
		}

		public Criteria andDatetimeGreaterThanOrEqualTo(Date value) {
			addCriterion("datetime >=", value, "datetime");
			return (Criteria) this;
		}

		public Criteria andDatetimeLessThan(Date value) {
			addCriterion("datetime <", value, "datetime");
			return (Criteria) this;
		}

		public Criteria andDatetimeLessThanOrEqualTo(Date value) {
			addCriterion("datetime <=", value, "datetime");
			return (Criteria) this;
		}

		public Criteria andDatetimeIn(List<Date> values) {
			addCriterion("datetime in", values, "datetime");
			return (Criteria) this;
		}

		public Criteria andDatetimeNotIn(List<Date> values) {
			addCriterion("datetime not in", values, "datetime");
			return (Criteria) this;
		}

		public Criteria andDatetimeBetween(Date value1, Date value2) {
			addCriterion("datetime between", value1, value2, "datetime");
			return (Criteria) this;
		}

		public Criteria andDatetimeNotBetween(Date value1, Date value2) {
			addCriterion("datetime not between", value1, value2, "datetime");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table property_value
	 * @mbggenerated  Tue Apr 07 19:01:45 CST 2015
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table property_value
     *
     * @mbggenerated do_not_delete_during_merge Thu Apr 02 16:15:13 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}