package hust.shop.pojo;

import java.io.Serializable;
import java.util.Date;

public class PropertyValue implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 18157684172716680L;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column property_value.id
	 * @mbggenerated  Tue Apr 07 19:01:45 CST 2015
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column property_value.product_property_id
	 * @mbggenerated  Tue Apr 07 19:01:45 CST 2015
	 */
	private Integer productPropertyId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column property_value.name
	 * @mbggenerated  Tue Apr 07 19:01:45 CST 2015
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column property_value.datetime
	 * @mbggenerated  Tue Apr 07 19:01:45 CST 2015
	 */
	private Date datetime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column property_value.id
	 * @return  the value of property_value.id
	 * @mbggenerated  Tue Apr 07 19:01:45 CST 2015
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column property_value.id
	 * @param id  the value for property_value.id
	 * @mbggenerated  Tue Apr 07 19:01:45 CST 2015
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column property_value.product_property_id
	 * @return  the value of property_value.product_property_id
	 * @mbggenerated  Tue Apr 07 19:01:45 CST 2015
	 */
	public Integer getProductPropertyId() {
		return productPropertyId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column property_value.product_property_id
	 * @param productPropertyId  the value for property_value.product_property_id
	 * @mbggenerated  Tue Apr 07 19:01:45 CST 2015
	 */
	public void setProductPropertyId(Integer productPropertyId) {
		this.productPropertyId = productPropertyId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column property_value.name
	 * @return  the value of property_value.name
	 * @mbggenerated  Tue Apr 07 19:01:45 CST 2015
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column property_value.name
	 * @param name  the value for property_value.name
	 * @mbggenerated  Tue Apr 07 19:01:45 CST 2015
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column property_value.datetime
	 * @return  the value of property_value.datetime
	 * @mbggenerated  Tue Apr 07 19:01:45 CST 2015
	 */
	public Date getDatetime() {
		return datetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column property_value.datetime
	 * @param datetime  the value for property_value.datetime
	 * @mbggenerated  Tue Apr 07 19:01:45 CST 2015
	 */
	public void setDatetime(Date datetime) {
		this.datetime = datetime;
	}
	/** add_y */
	ProductProperty productProperty;

	public ProductProperty getProductProperty() {
		return productProperty;
	}

	public void setProductProperty(ProductProperty productProperty) {
		this.productProperty = productProperty;
	}
	
	/** addend_y */
}