package hust.shop.pojo;

import java.util.Date;

public class Shop {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column shop.id
	 * @mbggenerated  Fri Apr 03 17:20:12 CST 2015
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column shop.user_id
	 * @mbggenerated  Fri Apr 03 17:20:12 CST 2015
	 */
	private Integer userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column shop.name
	 * @mbggenerated  Fri Apr 03 17:20:12 CST 2015
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column shop.level
	 * @mbggenerated  Fri Apr 03 17:20:12 CST 2015
	 */
	private Integer level;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column shop.time
	 * @mbggenerated  Fri Apr 03 17:20:12 CST 2015
	 */
	private Date time;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column shop.description
	 * @mbggenerated  Fri Apr 03 17:20:12 CST 2015
	 */
	private String description;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column shop.id
	 * @return  the value of shop.id
	 * @mbggenerated  Fri Apr 03 17:20:12 CST 2015
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column shop.id
	 * @param id  the value for shop.id
	 * @mbggenerated  Fri Apr 03 17:20:12 CST 2015
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column shop.user_id
	 * @return  the value of shop.user_id
	 * @mbggenerated  Fri Apr 03 17:20:12 CST 2015
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column shop.user_id
	 * @param userId  the value for shop.user_id
	 * @mbggenerated  Fri Apr 03 17:20:12 CST 2015
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column shop.name
	 * @return  the value of shop.name
	 * @mbggenerated  Fri Apr 03 17:20:12 CST 2015
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column shop.name
	 * @param name  the value for shop.name
	 * @mbggenerated  Fri Apr 03 17:20:12 CST 2015
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column shop.level
	 * @return  the value of shop.level
	 * @mbggenerated  Fri Apr 03 17:20:12 CST 2015
	 */
	public Integer getLevel() {
		return level;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column shop.level
	 * @param level  the value for shop.level
	 * @mbggenerated  Fri Apr 03 17:20:12 CST 2015
	 */
	public void setLevel(Integer level) {
		this.level = level;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column shop.time
	 * @return  the value of shop.time
	 * @mbggenerated  Fri Apr 03 17:20:12 CST 2015
	 */
	public Date getTime() {
		return time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column shop.time
	 * @param time  the value for shop.time
	 * @mbggenerated  Fri Apr 03 17:20:12 CST 2015
	 */
	public void setTime(Date time) {
		this.time = time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column shop.description
	 * @return  the value of shop.description
	 * @mbggenerated  Fri Apr 03 17:20:12 CST 2015
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column shop.description
	 * @param description  the value for shop.description
	 * @mbggenerated  Fri Apr 03 17:20:12 CST 2015
	 */
	public void setDescription(String description) {
		this.description = description;
	}
}